# Generated by Django 5.0.6 on 2024-07-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_lvl1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_lvl2', to='subone.categorylevel1')),
            ],
        ),
        migrations.AddField(
            model_name='categorylevel1',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_lvl1', to='subone.mcategory'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_lvl2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='subone.categorylevel2')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseOverview', to='subone.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('bio', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, default='400-200.png', upload_to='')),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseInstructor', to='subone.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseCurriculum', to='subone.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('batch_img', models.ImageField(blank=True, default='400-200.png', upload_to='')),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseBatch_details', to='subone.subcategory')),
            ],
        ),
    ]
