# Generated by Django 5.0.6 on 2024-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0003_categorylevel1_mcategory_categorylevel2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylevel1',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='categorylevel2',
            name='category_lvl1',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_lvl2',
        ),
        migrations.RemoveField(
            model_name='coursebatchdetails',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='coursecurriculum',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='courseinstructor',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='MCategory',
        ),
        migrations.DeleteModel(
            name='CategoryLevel1',
        ),
        migrations.DeleteModel(
            name='CategoryLevel2',
        ),
        migrations.DeleteModel(
            name='CourseBatchDetails',
        ),
        migrations.DeleteModel(
            name='CourseCurriculum',
        ),
        migrations.DeleteModel(
            name='CourseInstructor',
        ),
        migrations.DeleteModel(
            name='CourseOverview',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
