# Generated by Django 5.0.6 on 2024-07-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0005_maincategory_category_subcategory_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OV', 'Overview'), ('BA', 'Batches'), ('CU', 'Curriculum'), ('IN', 'Instructor')], max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='400-200.png', upload_to='img_uploads/')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='subone.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
