# Generated by Django 5.0.6 on 2024-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0006_sections_delete_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(choices=[('Overview', 'Overview'), ('Batches', 'Batches'), ('Curriculum', 'Curriculum'), ('Instructor', 'Instructor')], max_length=255),
        ),
    ]
