# Generated by Django 5.0.6 on 2024-07-08 08:26

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0007_alter_sections_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
