# Generated by Django 5.0.6 on 2024-07-08 09:42

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0008_alter_blog_desc_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='class_desc',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
