# Generated by Django 5.0.6 on 2024-07-08 09:51

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0009_alter_batches_class_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
