# Generated by Django 5.0.6 on 2024-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0010_alter_sections_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBannerResponsive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='400-200.png', upload_to='img_uploads/')),
                ('button_text', models.TextField()),
                ('hyperLink', models.TextField(default='paste-link')),
            ],
        ),
    ]
