# Generated by Django 5.0.6 on 2024-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0011_mainbannerresponsive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='course_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
