# Generated by Django 5.0.6 on 2024-07-09 10:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0012_alter_batches_course_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
