# Generated by Django 5.0.6 on 2024-07-09 10:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0013_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='class_desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='sections',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
