# Generated by Django 5.0.6 on 2024-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0014_alter_batches_class_desc_alter_blog_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchieversBannerResponsive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='400-200.png', upload_to='')),
            ],
        ),
    ]
