# Generated by Django 5.0.6 on 2024-07-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0015_achieversbannerresponsive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
